version: "3.8"

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  
    depends_on:
      - front-end
    deploy:
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - iot-network

  front-end:
    image: 182399716240.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
    depends_on:
      - back-end
    deploy:
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
    build:
      context: ./front-end
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - iot-network

  back-end:
    image: 182399716240.dkr.ecr.us-east-1.amazonaws.com/backend:latest  
    depends_on:
      - mosquitto
    deploy:
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
    ports:
      - 3000:3000
    build:
      context: ./back-end
      dockerfile: Dockerfile
    env_file:
      - ./back-end/.env
    environment:
      NODE_ENV: "production" 
    command: >
      sh -c 'if [ "$NODE_ENV" = "development" ]; then npm run dev;
      elif [ "$NODE_ENV" = "production" ]; then npm run start;
      else echo "Unknown NODE_ENV=$NODE_ENV"; exit 1; fi'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - iot-network


  mosquitto:
    image: 182399716240.dkr.ecr.us-east-1.amazonaws.com/mosquitto:latest  
    container_name: mosquitto
    deploy:
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", '$$SYS/#', "-C", "1", "-i", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - iot-network


networks:
  iot-network:
    driver: bridge
