services:

  nginx:
    image: 182399716240.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
    build:
      context: ./front-end
      dockerfile: nginx.Dockerfile
    ports:
      - 443:443
      - 80:80  
    depends_on:
      - back-end
    deploy:
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - iot-network

  # front-end:
  #   image: 182399716240.dkr.ecr.us-east-1.amazonaws.com/front-end:latest
  #   depends_on:
  #     - back-end
  #   deploy:
  #     replicas: 2
  #     update_config:
  #       order: start-first
  #       failure_action: rollback
  #       delay: 10s
  #     restart_policy:
  #       condition: any
  #       delay: 5s
  #   build:
  #     context: ./front-end
  #     dockerfile: Dockerfile
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 30s
  #   networks:
  #     - iot-network

  back-end:
    image: 182399716240.dkr.ecr.us-east-1.amazonaws.com/back-end:latest  
    depends_on:
      - mosquitto
    deploy:
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    secrets:
      - source: mqtt_ca_crt
        target: /run/secrets/mqtt_ca_crt
      - source: mqtt_client_csr_subject
        target: /run/secrets/mqtt_client_csr_subject
      - source: mqtt_ca_key
        target: /run/secrets/mqtt_ca_key
      - source: mqtt_ca_password
        target: /run/secrets/mqtt_ca_password
    ports:
      - target: 3000
        published: 3000
        mode: ingress
    build:           # for local development
      context: ./back-end      # for local development
      dockerfile: Dockerfile   # for local development
    env_file:
      - ./back-end/.env
    environment:
      NODE_ENV: "production" 
    # command: >
    #   sh -c 'if [ "$NODE_ENV" = "development" ]; then npm run dev;
    #   elif [ "$NODE_ENV" = "production" ]; then npm run start;
    #   else echo "Unknown NODE_ENV=$NODE_ENV"; exit 1; fi'
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - iot-network


  mosquitto:
    image: 182399716240.dkr.ecr.us-east-1.amazonaws.com/mosquitto:latest  
    deploy:
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
    secrets:
      - source: mqtt_ca_crt
        target: /run/secrets/mqtt_ca_crt
      - source: mqtt_ca_key
        target: /run/secrets/mqtt_ca_key
      - source: mqtt_server_crt
        target: /run/secrets/mqtt_server_crt
      - source: mqtt_server_key
        target: /run/secrets/mqtt_server_key
      - source: mqtt_ca_password
        target: /run/secrets/mqtt_ca_password
      - source: mqtt_crt_subject
        target: /run/secrets/mqtt_crt_subject
      - source: mqtt_csr_subject
        target: /run/secrets/mqtt_csr_subject
      - source: mqtt_client_csr_subject
        target: /run/secrets/mqtt_client_csr_subject
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    ports:
    - target: 1883
      published: 1883
      protocol: tcp
      mode: ingress
    - target: 9001
      published: 9001
      protocol: tcp
      mode: ingress
    volumes:
    - mosquitto_config:/mosquitto/config
    - mosquitto_data:/mosquitto/data
    - mosquitto_log:/mosquitto/log
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -t '$$SYS/#' -C 1 -i healthcheck || exit 1"]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - iot-network


networks:
  iot-network:
    driver: overlay
    attachable: true

secrets:
  mqtt_ca_crt:
    external: true
  mqtt_ca_key:
    external: true
  mqtt_server_crt:
    external: true
  mqtt_server_key:
    external: true
  mqtt_ca_password:
    external: true
  mqtt_crt_subject:
    external: true
  mqtt_csr_subject:
    external: true
  mqtt_client_csr_subject:
    external: true

volumes:
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
  volumes: