services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  
    depends_on:
      - front-end
      - back-end
      - mosquitto
    networks:
      - iot-network

  front-end:
    depends_on:
      - back-end
    container_name: front-end
    build:
      context: ./front-end
      dockerfile: Dockerfile
    restart: always
    networks:
      - iot-network

  back-end:
    depends_on:
      - influxdb
      - mosquitto
    container_name: back-end
    build:
      context: ./back-end
      dockerfile: Dockerfile
    env_file:
      - ./back-end/.env
    secrets:
      - influxdb_api_token
      - influxdb_admin_username
      - influxdb_admin_password
    environment:
      INFLUXDB_API_TOKEN_FILE: ./secrets/influxdb_api_token
      ADMIN_USERNAME_FILE: ./secrets/influxdb_admin_username
      ADMIN_PASSWORD_FILE: ./secrets/influxdb_admin_password
    volumes:
      - ./secrets/influxdb_api_token:./secrets/influxdb_api_token
      - ./secrets/influxdb_admin_username:./secrets/influxdb_admin_username
      - ./secrets/influxdb_admin_password:./secrets/influxdb_admin_password
    restart: always
    networks:
      - iot-network

  influxdb:
    container_name: influxdb
    build:
      context: ./influxdb
      dockerfile: Dockerfile
    ports:
      - 8086:8086
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    networks:
      - iot-network

  mosquitto:
    container_name: mosquitto
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    ports:
      - 1883:1883
      - 9001:9001
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - iot-network

secrets:
  influxdb_api_token:
    file: ./secrets/influxdb_api_token
  influxdb_admin_username:
    file: ./secrets/influxdb_admin_username
  influxdb_admin_password:
    file: ./secrets/influxdb_admin_password

networks:
  iot-network:
    driver: bridge

volumes:
  influxdb2-data:
  influxdb2-config: