
services:
  certbot:
    image: 182399716240.dkr.ecr.us-east-1.amazonaws.com/certbot:latest
    build:
      context: ./certbot
      dockerfile: Dockerfile
    volumes: 
      - /home/ubuntu/iot-server/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/iot-server/certbot/www:/var/www/certbot
    env_file:
      - ./certbot/.env
